[workspace]
members = [
  "met_binary",
  "met_connectors"
]

[workspace.package]
version = "0.2.1"
authors = ["Ingrid Rebecca Abraham <git@ingrids.email>"]
edition = "2021"
description = "System for real time spatial and timeseries quality control of weather data"
documentation = "https://docs.rs/rove"
readme = "README.md"
repository = "https://github.com/metno/rove"
license = "AGPL-3.0-only"
keywords = ["qc", "quality_control", "weather", "meteorology", "climate"]
categories = ["science::geo"]

[workspace.dependencies]
tonic = "0.14.3"
tokio = { version = "1.49.0", features = ["full"] }
prost-types = "0.14.3"
olympian = "0.5.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["tracing-log"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tempfile = "3.24.0"
tower = { version = "0.5.3", features = ["util"] }
thiserror = "2.0.18"
chrono = "0.4.43"
chronoutil = "0.2.7"
async-trait = "0.1.89"
tonic-prost-build = "0.14.3"
clap = { version = "4.5.56", features = ["derive"] }
criterion = { version = "0.8.1", features = ["async_tokio"] }
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json"] }
csv = "1.4.0"
toml = "0.9.11"
hyper-util = "0.1.19"
protobuf-src = "2.1.1"

[package]
name = "rove"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
exclude = [".github/", "ansible/", "deploy.sh", "docs", "python_client/"]

[dependencies]
tonic.workspace = true
tokio.workspace = true
olympian.workspace = true
tracing.workspace = true
tokio-stream.workspace = true
tower.workspace = true
thiserror.workspace = true
chrono.workspace = true
chronoutil.workspace = true
async-trait.workspace = true
serde.workspace = true
toml.workspace = true
prost-types.workspace = true
tonic-prost = "0.14.2"
prost = "0.14.1"

[build-dependencies]
tonic-prost-build.workspace = true
protobuf-src.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true
hyper-util.workspace = true

[[bench]]
name = "scalability_deliverable"
harness = false
