[workspace]
members = [
  "met_binary",
  "met_connectors"
]

[workspace.package]
version = "0.2.1"
authors = ["Ingrid Rebecca Abraham <git@ingrids.email>"]
edition = "2021"
description = "System for real time spatial and timeseries quality control of weather data"
documentation = "https://docs.rs/rove"
readme = "README.md"
repository = "https://github.com/metno/rove"
license = "AGPL-3.0-only"
keywords = ["qc", "quality_control", "weather", "meteorology", "climate"]
categories = ["science::geo"]

[workspace.dependencies]
tonic = "0.13.1"
tokio = { version = "1.46.1", features = ["full"] }
prost = "0.13.5"
prost-types = "0.13.5"
olympian = "0.5.1"
tracing = "0.1.16"
tracing-subscriber = { version = "0.3", features = ["tracing-log"] }
futures = "0.3.31"
tokio-stream = { version = "0.1.17", features = ["net"] }
tempfile = "3.20.0"
tower = { version = "0.5.2", features = ["util"] }
thiserror = "2.0.12"
chrono = "0.4.41"
chronoutil = "0.2.7"
async-trait = "0.1.88"
tonic-build = "0.13.1"
clap = { version = "4.5.42", features = ["derive"] }
criterion = { version = "0.5.1", features = ["async_tokio"] }
serde_json = "1.0.142"
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
csv = "1.3.1"
toml = "0.8.23"
hyper-util = "0.1.16"
protobuf-src = "2.1.1"

[package]
name = "rove"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
exclude = [".github/", "ansible/", "deploy.sh", "docs", "python_client/"]

[dependencies]
tonic.workspace = true
tokio.workspace = true
prost.workspace = true
prost-types.workspace = true
olympian.workspace = true
tracing.workspace = true
futures.workspace = true
tokio-stream.workspace = true
tower.workspace = true
thiserror.workspace = true
chrono.workspace = true
chronoutil.workspace = true
async-trait.workspace = true
serde.workspace = true
toml.workspace = true

[build-dependencies]
tonic-build.workspace = true
protobuf-src.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true
hyper-util.workspace = true

[[bench]]
name = "scalability_deliverable"
harness = false
