[package]
name = "lustre_netatmo"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rove = { path = ".." }
chrono.workspace = true
csv.workspace = true
async-trait.workspace = true
serde.workspace = true
tokio.workspace = true
