[package]
name = "lustre_netatmo"
version = "0.1.0"
edition = "2021"

[dependencies]
rove = { path = ".." }
chrono.workspace = true
csv.workspace = true
async-trait.workspace = true
serde.workspace = true
tokio.workspace = true
