# processing_sources:
#   - type: lard
#     station: "*" # match on all
#     paramcode: TA # 211/air_temperature 
#     time_resolution: PT1H
#     level: "*" # match on all
#     sensor: 0 # do we run the QC non default sensors? Maybe not at first?
[[steps]]
name = "special_value_check"
[steps.check.special_value_check]
special_values = [-999999, -6999, -99.9, -99.8, 999, 6999, 9999]

[[steps]]
name = "range_check"
[steps.check.range_check]
min = -55
max = 50

[[steps]]
name = "climate_range_check"
[steps.check.range_check_dynamic]
source = "netcdf" # TODO: define a neat spec for this?

[[steps]]
name = "step_check"
[steps.check.step_check]
max = 18.6

[[steps]]
name = "flatline_check"
[steps.check.flatline_check]
max = 10

[[steps]]
name = "spike_check"
[steps.check.spike_check]
max = 18.6

[[steps]]
name = "model_consistency_check"
[steps.check.model_consistency_check]
model_source = "lustre"
model_args = "arome/air_temperature" # TODO: verify if we need more args than this for the model
threshold = 3.0 # FIXME: made up value by Ingrid
