[package]
name = "frost"
version = "0.1.0"
edition = "2021"

[dependencies]
rove = { path = ".." }
async-trait.workspace = true
chrono.workspace = true
chronoutil.workspace = true
thiserror.workspace = true
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true