@startuml Confident_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

title
  Confident Container diagram
end title 

Person(user, "User", "Met employee")
Person(automated_user, "Automated User", "Cron or other automated system")

System_Ext(frost, "Frost", "Rest API")
SystemDb_Ext(oda, "ODA", "Observation database.")
SystemDb(lustre, "Lustre", "File system")

System_Boundary(Confident, "QC system for observations") {
  Container(controller, "Controller", "Controller for QC, knows the dependencies between QC tests and can schedule the dependencies as needed")
  Container(runner, "Runner", "The runner(s) contain the QC libraries and data cache, and can horizontally scale to run tests in parallel.")
}

Rel(controller, runner, "requests QC tests to be run by", "GRPC")
Rel(automated_user, oda, "writes flags to", "GRPC")

Rel(user, controller, "creates manual API calls to", "GRPC")
Rel(automated_user, controller, "creates automated API calls to", "GRPC")
Rel(runner, oda, "gets data needed for", "GRPC")
Rel(runner, lustre, "gets data needed for")
Rel(user, frost, "gets output of tests, data quality information from", "REST API")
@enduml