@startuml Confident_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

Person(user, "User", "User running tests through confident")
Person(automated_user, "Automated User", "System using confident to trigger tests")

'System(confident, "Confident", "System for running quality control tests on observation data")
System_Ext(frost, "Frost", "Rest API")
SystemDb_Ext(oda, "ODA", "Observation database.")
SystemDb(lustre, "Lustre", "File system")

System_Boundary(K8s, "Production (k8s)") {
  Container(controller, "Controller", "GRPC API used to control the running of tests")
  Container(runner, "Runner(s)", "Runner(s) which contain testing libraries and shared data cache")
}

Rel(controller, runner, "Controller requests test runs from runner(s)")
Rel(runner, controller, "Runner sends results back to controller")
Rel(controller, automated_user, "Controller sends aggregated results back to user")
Rel(controller, user, "Controller sends aggregated results back to user")
Rel(automated_user, oda, "Write flags to database")

Rel(user, controller, "Manual API calls")
Rel(automated_user, controller, "Cron jobs, YAML definitions for what tests should be run on new data etc.")
Rel(runner, oda, "Get data needed for cache")
Rel(runner, lustre, "Get data needed for cache")
Rel(user, frost, "Get output of tests, data quality information")
@enduml